# Generated by Django 2.2 on 2021-03-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], default=1, max_length=1, verbose_name='Security Approval Level')),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Approver',
                'verbose_name_plural': 'Approvers',
            },
        ),
        migrations.CreateModel(
            name='CountrySecurityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], max_length=1)),
            ],
            options={
                'verbose_name': 'Country Security Level',
                'verbose_name_plural': 'Countries Security Levels',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_traveler', models.CharField(choices=[('Employee', 'Employee'), ('Dependant', 'Consultant'), ('Consultant', 'Consultant'), ('Partners', 'Partners')], max_length=20)),
                ('nationality', models.CharField(max_length=30)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('contact_email', models.CharField(blank=True, max_length=70)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_approver', to='traveler.Approver')),
                ('country_of_duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.CountrySecurityLevel', verbose_name='Country of duty / residence')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.Departments')),
                ('is_managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Line_Manager', to='traveler.TravelerProfile', verbose_name='Line Manager')),
            ],
            options={
                'verbose_name': 'Traveler Profile',
                'verbose_name_plural': 'Travelers Profiles',
            },
        ),
    ]
