# Generated by Django 2.2 on 2021-01-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('trip_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_traveler', models.CharField(choices=[('Employee', 'Employee'), ('Dependant', 'Consultant'), ('Consultant', 'Consultant'), ('Partners', 'Partners')], max_length=20)),
                ('nationality', models.CharField(max_length=30)),
                ('country_of_duty', models.CharField(max_length=40, null=True, verbose_name='Country of duty / residence')),
                ('contact_telephone', models.CharField(max_length=20)),
                ('contact_email', models.CharField(blank=True, max_length=70)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_approver', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.Departments')),
                ('is_managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Line_Manager', to='traveler.TravelerProfile', verbose_name='Line Manager')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traveler Profile',
                'verbose_name_plural': 'Travelers Profiles',
            },
        ),
    ]
