# Generated by Django 2.2 on 2020-09-21 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_traveler', models.CharField(choices=[('Employee', 'Employee'), ('Dependant', 'Consultant'), ('Consultant', 'Consultant')], max_length=20)),
                ('nationality', models.CharField(max_length=30)),
                ('country_of_duty', models.CharField(blank=True, max_length=40)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.CharField(blank=True, max_length=70)),
                ('is_dependant_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traveler.TravelerDetails')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
