# Generated by Django 2.2 on 2021-01-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySecurityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], max_length=1)),
                ('security_level_3_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country Security Level',
                'verbose_name_plural': 'Countries Security Levels',
            },
        ),
        migrations.AlterField(
            model_name='travelerprofile',
            name='country_of_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.CountrySecurityLevel', verbose_name='Country of duty / residence'),
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], default=1, max_length=1, verbose_name='Security Approval Level')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approver',
                'verbose_name_plural': 'Approvers',
            },
        ),
    ]
