# Generated by Django 2.2 on 2021-01-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_auto_20210119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='approver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countrysecuritylevel',
            name='security_level_3_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.Approver'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='trip_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.Approver'),
        ),
        migrations.AlterField(
            model_name='travelerprofile',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_approver', to='traveler.Approver'),
        ),
    ]
