# Generated by Django 2.2 on 2020-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_auto_20200921_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='travelerdetails',
            name='contact_telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='travelerdetails',
            name='country_of_duty',
            field=models.CharField(max_length=40, verbose_name='Country of duty / residence'),
        ),
        migrations.AlterField(
            model_name='travelerdetails',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='travelerdetails',
            name='first_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
