# Generated by Django 2.2 on 2021-04-29 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_auto_20210323_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_delegation', models.TextField(max_length=500)),
                ('reason_for_revocation', models.TextField(max_length=500)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegating_approver', to='traveler.Approver')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegate', to='traveler.Approver')),
            ],
        ),
    ]
