# Generated by Django 2.2 on 2021-01-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_auto_20210121_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='trip_approver',
        ),
        migrations.AddField(
            model_name='departments',
            name='security_level_1_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_level_1_approver', to='traveler.Approver'),
        ),
        migrations.AddField(
            model_name='departments',
            name='security_level_2_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_level_2_approver', to='traveler.Approver'),
        ),
    ]
