# Generated by Django 2.2 on 2021-04-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_approvaldelegation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approver',
            old_name='approver',
            new_name='user',
        ),
    ]
