# Generated by Django 2.2 on 2020-09-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_auto_20200922_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerdetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traveler.DepartmentsModel'),
        ),
    ]
