# Generated by Django 2.2 on 2021-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_auto_20210121_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
