# Generated by Django 2.2 on 2021-04-30 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_auto_20210429_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
