# Generated by Django 2.2 on 2020-10-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_auto_20200924_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerdetails',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_approver', to='traveler.TravelerDetails'),
        ),
    ]
