# Generated by Django 2.2 on 2020-10-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0005_travelerdetails_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerdetails',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
