# Generated by Django 2.2 on 2020-10-29 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0008_auto_20201027_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelerdetails',
            name='country_of_duty',
        ),
        migrations.AlterField(
            model_name='travelerdetails',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.DepartmentsModel'),
        ),
    ]
