# Generated by Django 2.2 on 2020-09-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_travel', models.CharField(choices=[('Domestic', 'Domestic'), ('IntraContinental', 'IntraContinental'), ('International', 'International')], max_length=15)),
                ('categories_of_travel', models.CharField(choices=[('Business', 'Business'), ('Home Leave', 'Home Leave'), ('R & R', 'R & R'), ('Personal', 'Personal'), ('Medical', 'Medical'), ('Compassionate', 'Compassionate')], max_length=15)),
                ('mode_of_travel', models.CharField(choices=[('Air', 'Air'), ('Land', 'Land'), ('Water', 'Water')], max_length=10)),
                ('reason_for_travel', models.CharField(help_text='Use less than 1000 characters to describe the reasons for travel', max_length=1000)),
                ('is_mission_critical', models.BooleanField()),
                ('is_travel_completed', models.BooleanField(default=False)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.TravelerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TripTravelerDependants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependants_travelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.TravelerDetails')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dete_of_departure', models.DateTimeField()),
                ('time_of_departure', models.TimeField()),
                ('city_of_departure', models.CharField(max_length=40)),
                ('left_transit', models.BooleanField(default=False)),
                ('leg_status', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expense', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='TripApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trips')),
            ],
        ),
    ]
