# Generated by Django 2.2 on 2021-03-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(db_index=True, help_text='In at most 200 characters give your trip a descriptive\n                            title', max_length=200)),
                ('type_of_travel', models.CharField(choices=[('Domestic', 'Domestic'), ('IntraContinental', 'IntraContinental'), ('International', 'International')], max_length=20)),
                ('category_of_travel', models.CharField(choices=[('Business', 'Business'), ('Home Leave', 'Home Leave'), ('R & R', 'R & R'), ('Personal', 'Personal'), ('Medical', 'Medical'), ('Compassionate', 'Compassionate')], max_length=15)),
                ('reason_for_travel', models.CharField(help_text='Use less than 1000 characters to describe the reasons for travel', max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_mission_critical', models.BooleanField()),
                ('is_travel_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('scope_of_work', models.FileField(null=True, upload_to='media/uploads/scope_of_work/%Y/%m/%d/', verbose_name='Scope of Work')),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], default=1, max_length=1)),
                ('approval_complete', models.BooleanField(default=False, verbose_name='Is approval Complete?')),
                ('traveler', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='traveler.TravelerProfile')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='TripTravelerDependants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependants_travelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.TravelerProfile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPOET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(db_index=True, max_length=6)),
                ('task', models.CharField(max_length=3)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.Trip')),
            ],
            options={
                'verbose_name': 'Trip POET Details',
                'verbose_name_plural': 'Trip POET Details',
            },
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateField()),
                ('time_of_departure', models.TimeField()),
                ('city_of_departure', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=50)),
                ('mode_of_travel', models.CharField(choices=[('Air', 'Air'), ('Road', 'Road'), ('Water', 'Water')], max_length=10)),
                ('leg_status', models.CharField(choices=[('Complete', 'Incomplete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
            ],
            options={
                'verbose_name': 'Trip Itinerary',
                'verbose_name_plural': 'Trips Itineraries',
            },
        ),
        migrations.CreateModel(
            name='TripApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_request_date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(blank=True, default=True, verbose_name='Approval validity')),
                ('security_level', models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], default=1, max_length=1)),
                ('trip_is_approved', models.BooleanField(default=False, verbose_name='Approval')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='traveler.Approver', verbose_name='Approved by')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_approvals', to='trip.Trip')),
            ],
            options={
                'verbose_name': 'Trip Approval',
                'verbose_name_plural': 'Trips Approvals',
            },
        ),
    ]
