# Generated by Django 2.2 on 2021-01-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='countrysecuritylevel',
            name='security_level_3_approver',
        ),
        migrations.AddField(
            model_name='trip',
            name='approval_complete',
            field=models.BooleanField(default=False, verbose_name='Is approval Complete?'),
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='mode_of_travel',
            field=models.CharField(choices=[('Air', 'Air'), ('Road', 'Road'), ('Water', 'Water')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ApprovalGroups',
        ),
        migrations.DeleteModel(
            name='Approver',
        ),
        migrations.DeleteModel(
            name='CountrySecurityLevel',
        ),
    ]
