# Generated by Django 2.2 on 2020-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
