# Generated by Django 2.2 on 2021-04-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripapproval',
            name='acted_upon',
            field=models.BooleanField(blank=True, default=True, verbose_name='Approver has acted upon'),
        ),
    ]
