# Generated by Django 2.2 on 2021-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripapproval_acted_upon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripapproval',
            name='acted_upon',
            field=models.BooleanField(blank=True, default=False, verbose_name='Approver has acted upon'),
        ),
    ]
