# Generated by Django 2.2 on 2020-09-21 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trips_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripitinerary',
            name='dete_of_departure',
        ),
        migrations.AddField(
            model_name='tripitinerary',
            name='date_of_departure',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 12, 5, 37, 360012, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripapproval',
            name='approval_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
