# Generated by Django 2.2 on 2021-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20210119_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripapproval',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True, verbose_name='Approval validity'),
        ),
        migrations.AddField(
            model_name='tripapproval',
            name='security_level',
            field=models.CharField(choices=[('1', 'Level 1'), ('1', 'Level 2'), ('3', 'Level 3')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='tripapproval',
            name='approval_request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
