# Generated by Django 2.2 on 2020-09-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_auto_20200921_1629'),
        ('trip', '0004_auto_20200921_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traveler.TravelerDetails')),
            ],
        ),
    ]
