# Generated by Django 2.2 on 2020-09-28 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_approvalgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 11, 29, 44, 299346, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 11, 29, 55, 4142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
