# Generated by Django 2.2 on 2021-02-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210126_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripapproval',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_approvals', to='trip.Trip'),
        ),
    ]
