# Generated by Django 2.2 on 2021-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20210215_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type_of_travel',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('IntraContinental', 'IntraContinental'), ('International', 'International')], max_length=20),
        ),
    ]
