# Generated by Django 2.2 on 2020-09-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20200928_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='trip_name',
            field=models.CharField(db_index=True, default='New trip', help_text='In less than 200 characters give your trip a descriptive\n                                title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripapproval',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trip.Trips'),
        ),
    ]
