# Generated by Django 2.2 on 2020-09-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20200930_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='categories_of_travel',
            new_name='category_of_travel',
        ),
    ]
