# Generated by Django 2.2 on 2020-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20200930_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripitinerary',
            name='left_transit',
        ),
        migrations.AddField(
            model_name='tripitinerary',
            name='destination',
            field=models.CharField(default='Kisumu', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='leg_status',
            field=models.CharField(max_length=10),
        ),
    ]
