# Generated by Django 2.2 on 2020-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_auto_20200930_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitinerary',
            name='mode_of_travel',
            field=models.CharField(choices=[('Air', 'Air'), ('Land', 'Land'), ('Water', 'Water')], default='Air', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripitinerary',
            name='leg_status',
            field=models.CharField(choices=[('Complete', 'Incomplete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10),
        ),
    ]
