# Generated by Django 2.2 on 2020-10-13 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20200930_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripapproval',
            name='approval_request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripapproval',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
