# Generated by Django 2.2 on 2020-10-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_auto_20201013_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripapproval',
            name='approval_comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='tripapproval',
            name='trip_is_approved',
            field=models.BooleanField(default=False, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='traveler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='traveler.TravelerDetails'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_name',
            field=models.CharField(db_index=True, help_text='In at most 200 characters give your trip a descriptive\n                                title', max_length=200),
        ),
    ]
