# Generated by Django 2.2 on 2020-11-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_auto_20201106_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='mode_of_travel',
        ),
    ]
