# Generated by Django 2.2 on 2020-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_remove_trips_mode_of_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='scope_of_work',
            field=models.FileField(null=True, upload_to='uploads/scope_of_work/%Y/%m/%d/', verbose_name='Scope of Work'),
        ),
    ]
